-- 1. Agregar columna VIP a usuarios
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS is_vip BOOLEAN DEFAULT FALSE;

-- 2. Crear tabla de Reservas
CREATE TABLE IF NOT EXISTS public.reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'APPROVED' CHECK (status IN ('APPROVED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Habilitar RLS (Row Level Security)
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de Seguridad (RLS)

-- Todos pueden ver las reservas (para consultar disponibilidad)
CREATE POLICY "Todos pueden ver reservas" 
ON public.reservations FOR SELECT 
USING (true);

-- Usuarios autenticados pueden crear reservas
CREATE POLICY "Usuarios pueden crear reservas" 
ON public.reservations FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Dueño o Admin puede actualizar (para cancelar)
CREATE POLICY "Dueño o Admin puede actualizar" 
ON public.reservations FOR UPDATE 
USING (auth.uid() = user_id OR EXISTS (
    SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'
));
