-- 1. Tabla de Planificación Semanal de Turnos
CREATE TABLE IF NOT EXISTS public.weekly_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start_date DATE NOT NULL, -- Lunes de la semana correspondiente
  
  -- Configuración de Horario (JSONB)
  -- Estructura esperada:
  -- {
  --   "mon": { "start": "08:00", "end": "12:00", "break_start": "12:00", "break_end": "14:00", "end2": "18:00" },
  --   "tue": ...
  -- }
  schedule_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  
  -- Campos para horas extra manuales aprobadas previamente (opcional)
  overtime_hours NUMERIC(5,2) DEFAULT 0,
  overtime_notes TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Restricción: Un solo horario por usuario por semana
  UNIQUE(user_id, week_start_date)
);

-- 2. Tabla de Sesiones de Trabajo (Control de Asistencia)
CREATE TABLE IF NOT EXISTS public.work_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  session_start TIMESTAMPTZ DEFAULT NOW(),
  session_end TIMESTAMPTZ, -- Se actualiza al cerrar sesión o por heartbeat
  
  -- Duración calculada (opcional, se puede calcular en query)
  -- duration_minutes INTEGER GENERATED ALWAYS AS (EXTRACT(EPOCH FROM (session_end - session_start))/60) STORED,
  
  -- Auditoría y Reglas Avanzadas
  ip_address TEXT,
  user_agent TEXT,         -- Para distinguir PC vs Móvil vs Tablet
  device_fingerprint TEXT, -- Hash simple si se implementa
  
  is_overtime BOOLEAN DEFAULT FALSE,   -- Marcado si la sesión excede el horario
  auto_closed BOOLEAN DEFAULT FALSE,   -- Si se cerró por timeout del sistema
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Políticas de Seguridad (RLS)
ALTER TABLE public.weekly_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_sessions ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS: weekly_schedules
-- Admins pueden ver y editar todo
CREATE POLICY "Admins can manage all schedules" ON public.weekly_schedules
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT id FROM public.users WHERE role IN ('admin', 'superadmin')
    )
  );

-- Usuarios pueden ver sus propios horarios
CREATE POLICY "Users can view own schedules" ON public.weekly_schedules
  FOR SELECT
  USING (auth.uid() = user_id);

-- POLÍTICAS: work_sessions
-- Admins pueden ver todo
CREATE POLICY "Admins can view all sessions" ON public.work_sessions
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM public.users WHERE role IN ('admin', 'superadmin')
    )
  );

-- Usuarios pueden ver e insertar sus propias sesiones
CREATE POLICY "Users can manage own sessions" ON public.work_sessions
  FOR ALL
  USING (auth.uid() = user_id);

-- Indices para rendimiento
CREATE INDEX IF NOT EXISTS idx_weekly_schedules_user_week ON public.weekly_schedules(user_id, week_start_date);
CREATE INDEX IF NOT EXISTS idx_work_sessions_user_date ON public.work_sessions(user_id, session_start);
