-- Tabla para definir los tipos de turnos disponibles
CREATE TABLE IF NOT EXISTS public.shift_presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE
);

-- Insertar valores por defecto iniciales
INSERT INTO public.shift_presets (label, start_time, end_time) 
VALUES 
    ('Mañana (6am - 2pm)', '06:00', '14:00'),
    ('Tarde (2pm - 10pm)', '14:00', '22:00'),
    ('Noche (10pm - 6am)', '22:00', '06:00'),
    ('Oficina (8am - 5pm)', '08:00', '17:00')
ON CONFLICT DO NOTHING; -- No hay constraint unico por defecto, pero previene errores si re-ejecutamos con logica simple

-- RLS: Admin puede gestionar, todos pueden leer
ALTER TABLE public.shift_presets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage presets" ON public.shift_presets
FOR ALL
TO authenticated
USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND (role = 'admin' OR role = 'superadmin'))
)
WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND (role = 'admin' OR role = 'superadmin'))
);

CREATE POLICY "Everyone reads presets" ON public.shift_presets
FOR SELECT
TO authenticated
USING (true);
