-- Migration: Create Ticket Audit Table (Traceability)

-- 1. Create Action Type Enum
DO $$ BEGIN
    CREATE TYPE audit_action_type_enum AS ENUM ('CREATED', 'STATUS_CHANGE', 'PAUSED', 'RESUMED', 'COMMENT_ADDED', 'RECLASSIFIED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Create Table
CREATE TABLE IF NOT EXISTS public.ticket_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES public.users(id), -- Agent who performed the action
    action_type audit_action_type_enum NOT NULL,
    old_value TEXT,
    new_value TEXT,
    comment TEXT, -- Justification or Note
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Index
CREATE INDEX IF NOT EXISTS idx_ticket_events_ticket_id ON public.ticket_events(ticket_id);
