-- Tabla de historial de activos (Trazabilidad)
CREATE TABLE IF NOT EXISTS public.asset_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_serial TEXT NOT NULL,
    event_type TEXT NOT NULL, -- 'CREATED', 'UPDATED', 'ASSIGNED', 'TRANSFERRED', 'DECOMMISSIONED'
    description TEXT,
    actor_id UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_asset_events_serial ON public.asset_events(asset_serial);
CREATE INDEX IF NOT EXISTS idx_asset_events_created_at ON public.asset_events(created_at);

-- RLS
ALTER TABLE public.asset_events ENABLE ROW LEVEL SECURITY;

-- Todos pueden ver historial (o restringir a staff?) - Por ahora todos autenticados
DROP POLICY IF EXISTS "Ver historial activos (Autenticados)" ON public.asset_events;
CREATE POLICY "Ver historial activos (Autenticados)" ON public.asset_events FOR SELECT TO authenticated USING (true);

-- Solo staff puede insertar eventos
DROP POLICY IF EXISTS "Crear historial activos (Staff)" ON public.asset_events;
CREATE POLICY "Crear historial activos (Staff)" ON public.asset_events FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin', 'agent', 'superadmin', 'staff'))
);
